2025-03-01 17:03:23,760 INFO    MainThread:33296 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\User\Desktop\ML_projects\My_repo\wandb\run-20250301_170323-dxuhj4od\logs\debug.log
2025-03-01 17:03:23,760 INFO    MainThread:33296 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\User\Desktop\ML_projects\My_repo\wandb\run-20250301_170323-dxuhj4od\logs\debug-internal.log
2025-03-01 17:03:23,760 INFO    MainThread:33296 [wandb_init.py:init():761] calling init triggers
2025-03-01 17:03:23,760 INFO    MainThread:33296 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'epochs': 10, 'batch': 32, 'imgsz': 640, 'workers': 4, '_wandb': {}}
2025-03-01 17:03:23,760 INFO    MainThread:33296 [wandb_init.py:init():784] starting backend
2025-03-01 17:03:23,767 INFO    MainThread:33296 [wandb_init.py:init():788] sending inform_init request
2025-03-01 17:03:23,771 INFO    MainThread:33296 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-01 17:03:23,772 INFO    MainThread:33296 [wandb_init.py:init():803] backend started and connected
2025-03-01 17:03:23,774 INFO    MainThread:33296 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-01 17:03:23,789 INFO    MainThread:33296 [wandb_init.py:init():896] updated telemetry
2025-03-01 17:03:23,841 INFO    MainThread:33296 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-01 17:03:24,469 ERROR   MainThread:33296 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\User\Desktop\ML_projects\My_repo\.venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\ML_projects\My_repo\.venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 968, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-03-01 17:09:58,757 INFO    MainThread:33296 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\User\Desktop\ML_projects\My_repo\wandb\run-20250301_170958-q8v5uc7u\logs\debug.log
2025-03-01 17:09:58,758 INFO    MainThread:33296 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\User\Desktop\ML_projects\My_repo\wandb\run-20250301_170958-q8v5uc7u\logs\debug-internal.log
2025-03-01 17:09:58,758 INFO    MainThread:33296 [wandb_init.py:init():761] calling init triggers
2025-03-01 17:09:58,759 INFO    MainThread:33296 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'epochs': 10, 'batch': 32, 'imgsz': 640, 'workers': 4, '_wandb': {}}
2025-03-01 17:09:58,759 INFO    MainThread:33296 [wandb_init.py:init():784] starting backend
2025-03-01 17:09:58,763 INFO    MainThread:33296 [wandb_init.py:init():788] sending inform_init request
2025-03-01 17:09:58,766 INFO    MainThread:33296 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-01 17:09:58,767 INFO    MainThread:33296 [wandb_init.py:init():803] backend started and connected
2025-03-01 17:09:58,769 INFO    MainThread:33296 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-01 17:09:58,781 INFO    MainThread:33296 [wandb_init.py:init():896] updated telemetry
2025-03-01 17:09:58,832 INFO    MainThread:33296 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-01 17:11:28,847 WARNING MainThread:33296 [wandb_init.py:init():1475] interrupted
Traceback (most recent call last):
  File "c:\Users\User\Desktop\ML_projects\My_repo\.venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\ML_projects\My_repo\.venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 946, in init
    result = wait_with_progress(
             ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\ML_projects\My_repo\.venv\Lib\site-packages\wandb\sdk\mailbox\wait_with_progress.py", line 23, in wait_with_progress
    return wait_all_with_progress(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\ML_projects\My_repo\.venv\Lib\site-packages\wandb\sdk\mailbox\wait_with_progress.py", line 86, in wait_all_with_progress
    return asyncio_compat.run(progress_loop_with_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\User\Desktop\ML_projects\My_repo\.venv\Lib\site-packages\wandb\sdk\lib\asyncio_compat.py", line 30, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 451, in result
    self._condition.wait(timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 355, in wait
    waiter.acquire()
KeyboardInterrupt
